name: Deploy to Lightsail

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - master  # Change this to the branch you're working with, if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # This job will run on an Ubuntu runner

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH to authenticate with your Lightsail instance
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private key to GitHub secrets

      # Step 3: Deploy code to Lightsail
      - name: Deploy to Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@35.154.69.62 << 'EOF'
            cd SeenInDark
            git pull origin master  # Pull the latest changes from your repository
            sudo systemctl restart gunicorn  # Restart the Gunicorn service
            sudo systemctl restart nginx  # Restart the Nginx service
          EOF
